[package]
name = "ip_update_checker"
version = "0.1.0"
edition = "2024"

[dependencies]
directories = "6.0.0"
lettre = "0.11.18"
lettre_email = "0.9.4"
once_cell = "1.21.3"
serde_json = "1.0.145"
tokio = { version = "1.47.1", features = ["full"] }
